In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

ICU = pd.read_csv('Preprocessed ICU data.csv')
print(ICU.shape)

(1474, 232)

# Missing values

In [2]:
missing_counts = ICU.isnull().sum()

print(missing_counts[missing_counts > 0] if missing_counts.sum() > 0 else "No missing values found")

No missing values found

# Duplicated row and column

In [3]:
# Check which columns are duplicates of an earlier column
duplicate_column_mask = ICU.T.duplicated()

# Get the names of the duplicate columns
duplicate_columns = ICU.columns[duplicate_column_mask].tolist()
print("Identical columns found:", duplicate_columns)

# Map each duplicate column to its original match
for col in duplicate_columns:
    for original in ICU.columns:
        # Find the first column that matches it (and isn't itself)
        if original != col and ICU[col].equals(ICU[original]):
            print(f"'{col}' is identical to '{original}'")
            break

Identical columns found: ['Min_MechVent.x', 'Max_MechVent.x', 'Mean_MechVent.y', 'Min_MechVent.y', 'Max_MechVent.y']
'Min_MechVent.x' is identical to 'Mean_MechVent.x'
'Max_MechVent.x' is identical to 'Mean_MechVent.x'
'Mean_MechVent.y' is identical to 'Mean_MechVent.x'
'Min_MechVent.y' is identical to 'Mean_MechVent.x'
'Max_MechVent.y' is identical to 'Mean_MechVent.x'

In [4]:
ICU = ICU.drop_duplicates()
print(ICU.shape)

(1474, 232)

# Identify odd values

In [5]:
print(ICU.dtypes)

RecordID               int64
Age                    int64
Gender               float64
Height               float64
ICUType2               int64
                      ...
Max_TroponinI.y      float64
Max_TroponinT.y      float64
SAPS.I                 int64
SOFA                   int64
In.hospital_death      int64
Length: 232, dtype: object

### Gender

In [6]:
print(ICU['Gender'].unique())

[1.         0.         0.56192144]

We found an invalid value (0.56192144) in the Gender column, which likely came from a mean imputation. 

We removed these rows using .isin() to keep only the valid binary values (0 and 1).

In [7]:
ICU = ICU[ICU['Gender'].isin([1,0])].copy()
print(ICU['Gender'].unique())

[1. 0.]

### SOFA & SAPS.I

In [8]:
ICU[ICU['SOFA'] == -1]

,RecordID,Age,Gender,Height,ICUType2,ICUType3,ICUType4,Mean_Weight.x,Mean_GCS.x,Mean_HR.x,...,Max_ALT.y,Max_AST.y,Max_Bilirubin.y,Max_Lactate.y,Max_Cholesterol.y,Max_TroponinI.y,Max_TroponinT.y,SAPS.I,SOFA,In.hospital_death
16,132610,72,1.0,172.900000,0,1,0,72.260000,15.000000,74.346154,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
58,132929,71,0.0,162.600000,0,1,0,113.800000,15.000000,110.956522,...,14.000000,46.000000,2.500000,11.500000,156.842105,7.132683,0.040000,13,-1,1
113,133399,50,1.0,175.300000,0,0,1,114.406818,5.125000,79.862069,...,26.000000,18.000000,1.900000,1.900000,156.842105,7.132683,1.114629,19,-1,1
117,133430,40,1.0,167.600000,0,1,0,199.744444,13.400000,81.185185,...,189.169186,260.323666,1.979557,1.400000,156.842105,7.132683,1.114629,9,-1,0
128,133485,73,0.0,167.600000,0,0,1,66.493548,11.818182,120.130435,...,189.169186,260.323666,1.979557,0.800000,216.000000,7.132683,1.114629,16,-1,0
152,133628,88,1.0,169.787227,0,1,0,83.054136,11.117704,96.000000,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
185,133834,90,0.0,169.787227,0,1,0,56.500000,12.400000,103.607143,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
259,134404,90,0.0,154.900000,0,1,0,68.500000,10.857143,99.826087,...,27.000000,23.000000,2.400000,1.900000,156.842105,7.132683,0.070000,19,-1,0
309,134663,81,0.0,169.787227,0,1,0,60.000000,6.111111,74.375000,...,189.169186,260.323666,1.979557,2.395461,156.842105,0.800000,1.114629,21,-1,0
312,134684,79,0.0,154.900000,0,0,0,75.000000,15.000000,83.794118,...,17.000000,24.000000,0.300000,0.700000,116.000000,7.132683,0.230000,14,-1,0
323,134754,81,0.0,157.500000,0,1,0,77.400000,11.200000,107.000000,...,189.169186,260.323666,1.979557,5.100000,156.842105,7.132683,1.114629,14,-1,0
413,135362,70,1.0,170.200000,0,0,0,90.200000,4.909091,78.370370,...,158.000000,143.000000,0.500000,2.395461,156.842105,42.900000,1.114629,22,-1,0
507,135972,70,1.0,169.787227,0,1,0,89.000000,8.000000,74.375000,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
515,136022,74,0.0,169.787227,0,1,0,83.054136,11.117704,87.243231,...,91.000000,66.000000,0.400000,9.400000,156.842105,7.132683,1.114629,-1,-1,0
524,136059,82,1.0,169.787227,0,1,0,91.281633,5.571429,91.033333,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,21,-1,0
697,137264,34,0.0,157.500000,0,0,1,111.000000,14.294118,94.729730,...,189.169186,260.323666,1.979557,2.300000,156.842105,7.132683,1.114629,8,-1,1
720,137447,73,1.0,180.300000,0,0,0,79.900000,15.000000,104.974359,...,3212.000000,6768.000000,1.700000,12.800000,133.000000,7.132683,5.620000,14,-1,1
832,138134,48,0.0,170.200000,0,1,0,158.000000,5.125000,102.169492,...,180.000000,84.000000,0.900000,2.300000,216.000000,7.132683,1.114629,18,-1,0
852,138269,42,0.0,169.787227,0,1,0,83.054136,11.117704,87.243231,...,16.000000,16.000000,1.000000,2.395461,156.842105,7.132683,1.114629,-1,-1,0
897,138527,51,1.0,169.787227,0,1,0,83.054136,11.117704,87.243231,...,189.169186,260.323666,1.979557,2.500000,156.842105,7.132683,1.114629,-1,-1,0
974,139039,37,0.0,169.787227,0,0,0,60.000000,14.750000,119.454545,...,383.000000,483.000000,1.400000,2.395461,156.842105,7.132683,1.114629,14,-1,1
978,139060,42,1.0,169.787227,0,0,0,83.054136,11.117704,87.243231,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
1006,139214,77,1.0,182.900000,0,0,1,78.500000,14.923077,73.200000,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,9,-1,0
1036,139433,30,1.0,169.787227,0,0,1,90.000000,6.571429,84.750000,...,44.000000,125.000000,1.100000,2.100000,156.842105,7.132683,0.100000,22,-1,1
1075,139722,77,1.0,170.200000,0,0,1,77.000000,7.684211,84.902439,...,60.000000,165.000000,0.200000,1.500000,156.842105,7.132683,1.114629,19,-1,1
1083,139781,77,1.0,169.787227,0,0,0,65.300000,15.000000,91.476190,...,55.000000,268.000000,0.500000,2.395461,154.000000,7.132683,1.114629,8,-1,0
1091,139838,56,0.0,169.787227,0,0,1,145.000000,3.315789,79.291667,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
1098,139881,74,0.0,169.787227,0,1,0,57.190909,10.000000,85.818182,...,189.169186,260.323666,1.979557,0.900000,156.842105,7.132683,0.010000,14,-1,0
1115,140025,75,0.0,169.787227,0,0,1,67.600000,5.736842,91.666667,...,189.169186,260.323666,1.979557,1.100000,156.842105,7.132683,1.114629,12,-1,0
1245,140997,90,0.0,169.787227,0,0,1,73.000000,15.000000,99.800000,...,65.000000,26.000000,5.300000,1.600000,156.842105,7.132683,1.114629,13,-1,1
1302,141416,77,0.0,160.000000,0,0,1,76.266667,7.571429,64.281250,...,189.169186,260.323666,1.979557,1.000000,156.842105,7.132683,1.114629,24,-1,0
1303,141424,64,0.0,169.787227,0,1,0,74.300000,9.714286,61.000000,...,171.000000,128.000000,0.300000,3.500000,84.000000,7.132683,0.460000,-1,-1,1
1328,141578,86,1.0,169.787227,0,0,0,83.054136,11.117704,87.243231,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
1350,141740,68,1.0,172.700000,0,0,1,92.175862,3.000000,79.555556,...,1000.000000,1190.000000,14.600000,1.700000,156.842105,7.132683,14.250000,23,-1,1
1352,141772,70,1.0,165.100000,0,1,0,69.000000,15.000000,102.100000,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,0.220000,-1,-1,0
1364,141821,88,0.0,169.787227,0,0,1,61.900000,9.882353,78.348837,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
1381,141959,88,0.0,169.787227,0,1,0,83.054136,14.375000,70.208333,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,-1,-1,0
1393,142061,82,0.0,169.787227,0,0,0,83.054136,11.117704,87.243231,...,189.169186,260.323666,1.979557,2.395461,156.842105,8.000000,1.114629,-1,-1,0
1435,142405,50,1.0,182.900000,0,0,0,127.000000,12.857143,95.309524,...,189.169186,260.323666,1.979557,10.500000,156.842105,7.132683,3.230000,18,-1,0

In [9]:
minus_one_counts = (ICU == -1).sum()

# Filter to show only columns that have at least one -1
columns_with_minus_one = minus_one_counts[minus_one_counts > 0]

if not columns_with_minus_one.empty:
    print("Columns containing -1: ")
    print(columns_with_minus_one)
else:
    print("No columns contain the value -1.")

Columns containing -1:
SAPS.I    71
SOFA      39
dtype: int64

In [10]:
print(ICU[['SAPS.I', 'SOFA']].head(20))

    SAPS.I  SOFA
0        7     1
1       17     2
2       14    11
3       19     8
4       11     0
5       12     3
6       18     6
7        9     2
8       28    16
9       -1     7
10      17    11
11      10     2
12      -1     5
13      22     5
14      13     1
15      21     9
16      -1    -1
17       8     3
18      20    10
19       8     5

In [11]:
ICU['SAPS.I'] = ICU['SAPS.I'].replace(-1, np.nan)
ICU['SOFA'] = ICU['SOFA'].replace(-1, np.nan)

features = ['Age', 'SAPS.I', 'SOFA']
X = ICU[features].copy()

Xm = X.mean()
Xs = X.std()

X_scaled = (X - Xm) / Xs

imputer = KNNImputer(n_neighbors=5)
Xt_scaled = imputer.fit_transform(X_scaled)

Xt_original = (Xt_scaled * Xs.values) + Xm.values

ICU[features] = Xt_original

ICU['SAPS.I'] = ICU['SAPS.I'].round().astype(int)
ICU['SOFA'] = ICU['SOFA'].round().astype(int)

In [12]:
# Make sure there is no more -1 

ICU[ICU['SOFA'] == -1]
ICU[ICU['SAPS.I'] == -1]

Empty DataFrame
Columns: [RecordID, Age, Gender, Height, ICUType2, ICUType3, ICUType4, Mean_Weight.x, Mean_GCS.x, Mean_HR.x, Mean_NIDiasABP.x, Mean_NIMAP.x, Mean_NISysABP.x, Mean_RespRate.x, Mean_Temp.x, Mean_Urine.x, Mean_BUN.x, Mean_Creatinine.x, Mean_Glucose.x, Mean_HCO3.x, Mean_GCT.x, Mean_Mg.x, Mean_Platelets.x, Mean_K.x, Mean_Na.x, Mean_WBC.x, Mean_pH.x, Mean_PaCO2.x, Mean_PaO2.x, Mean_DiasABP.x, Mean_FiO2.x, Mean_MAP.x, Mean_MechVent.x, Mean_SysABP.x, Mean_SaO2.x, Mean_Albumin.x, Mean_ALP.x, Mean_ALT.x, Mean_AST.x, Mean_Bilirubin.x, Mean_Lactate.x, Mean_Cholesterol.x, Mean_TroponinI.x, Mean_TroponinT.x, Min_Weight.x, Min_GCS.x, Min_HR.x, Min_NIDiasABP.x, Min_NIMAP.x, Min_NISysABP.x, Min_RespRate.x, Min_Temp.x, Min_Urine.x, Min_BUN.x, Min_Creatinine.x, Min_Glucose.x, Min_HCO3.x, Min_GCT.x, Min_Mg.x, Min_Platelets.x, Min_K.x, Min_Na.x, Min_WBC.x, Min_pH.x, Min_PaCO2.x, Min_PaO2.x, Min_DiasABP.x, Min_FiO2.x, Min_MAP.x, Min_MechVent.x, Min_SysABP.x, Min_SaO2.x, Min_Albumin.x, Min_ALP.x, Min_ALT.x, Min_AST.x, Min_Bilirubin.x, Min_Lactate.x, Min_Cholesterol.x, Min_TroponinI.x, Min_TroponinT.x, Max_Weight.x, Max_GCS.x, Max_HR.x, Max_NIDiasABP.x, Max_NIMAP.x, Max_NISysABP.x, Max_RespRate.x, Max_Temp.x, Max_Urine.x, Max_BUN.x, Max_Creatinine.x, Max_Glucose.x, Max_HCO3.x, Max_GCT.x, Max_Mg.x, Max_Platelets.x, Max_K.x, Max_Na.x, Max_WBC.x, ...]
Index: []

[0 rows x 232 columns]

In [13]:
print(ICU[['SAPS.I', 'SOFA']].head(20))

    SAPS.I  SOFA
0        7     1
1       17     2
2       14    11
3       19     8
4       11     0
5       12     3
6       18     6
7        9     2
8       28    16
9       15     7
10      17    11
11      10     2
12      15     5
13      22     5
14      13     1
15      21     9
16      18     6
17       8     3
18      20    10
19       8     5

### Height

In [14]:
# Check unusually low Height values
ICU[ICU['Height'] < 54.6]

,RecordID,Age,Gender,Height,ICUType2,ICUType3,ICUType4,Mean_Weight.x,Mean_GCS.x,Mean_HR.x,...,Max_ALT.y,Max_AST.y,Max_Bilirubin.y,Max_Lactate.y,Max_Cholesterol.y,Max_TroponinI.y,Max_TroponinT.y,SAPS.I,SOFA,In.hospital_death
660,136967,88.0,0.0,13.7,0,0,1,99.3,15.000000,97.454545,...,189.169186,260.323666,1.200000,1.2,156.842105,7.132683,1.114629,13,3,0
950,138870,58.0,1.0,15.2,0,0,1,124.0,8.857143,87.875000,...,189.169186,260.323666,1.979557,1.2,156.842105,7.132683,1.114629,14,6,0

We identified two unusually low outliers in the height column (13.7 cm and 15.2 cm). 

Assuming these are typo where a decimal point was misplaced, we corrected them by shifting the decimal one place to the right.

13.7 is likely meant to be 137.0 cm and 15.2 is likely meant to be 152.0 cm

In [15]:
ICU.loc[ICU['Height'] == 13.7, 'Height'] = 137.0
ICU.loc[ICU['Height'] == 15.2, 'Height'] = 152.0

In [16]:
# Check strange Height values
ICU[ICU['Height'] > 272]

,RecordID,Age,Gender,Height,ICUType2,ICUType3,ICUType4,Mean_Weight.x,Mean_GCS.x,Mean_HR.x,...,Max_ALT.y,Max_AST.y,Max_Bilirubin.y,Max_Lactate.y,Max_Cholesterol.y,Max_TroponinI.y,Max_TroponinT.y,SAPS.I,SOFA,In.hospital_death
165,133693,87.0,0.0,365.8,0,0,0,83.054136,14.0,59.086957,...,189.169186,260.323666,0.7,2.395461,156.842105,7.132683,1.114629,12,2,0
1173,140479,50.0,0.0,419.1,0,0,0,67.600000,9.2,80.263158,...,111.000000,168.000000,0.8,3.400000,205.000000,7.132683,1.114629,18,9,0

Conversely, the extreme high values (>272 cm) cannot be reconstructed as a simple typo. 

Therefore, we will convert them to NaN and handle them using KNN imputer.

In [18]:
ICU.loc[ICU['Height'] > 272, 'Height'] = np.nan

features_2 = ['Age', 'Height']
X_height = ICU[features_2].copy()

Xm_height = X_height.mean()
Xs_height = X_height.std()

X_scaled_height = (X_height - Xm_height) / Xs_height

imputer_height = KNNImputer(n_neighbors=5)
Xt_scaled_height = imputer_height.fit_transform(X_scaled_height)

Xt_original_height = (Xt_scaled_height * Xs_height.values) + Xm_height.values

ICU['Height'] = Xt_original_height[:, 1]

In [19]:
ICU[(ICU['Height'] < 100) | (ICU['Height'] > 250)]

Empty DataFrame
Columns: [RecordID, Age, Gender, Height, ICUType2, ICUType3, ICUType4, Mean_Weight.x, Mean_GCS.x, Mean_HR.x, Mean_NIDiasABP.x, Mean_NIMAP.x, Mean_NISysABP.x, Mean_RespRate.x, Mean_Temp.x, Mean_Urine.x, Mean_BUN.x, Mean_Creatinine.x, Mean_Glucose.x, Mean_HCO3.x, Mean_GCT.x, Mean_Mg.x, Mean_Platelets.x, Mean_K.x, Mean_Na.x, Mean_WBC.x, Mean_pH.x, Mean_PaCO2.x, Mean_PaO2.x, Mean_DiasABP.x, Mean_FiO2.x, Mean_MAP.x, Mean_MechVent.x, Mean_SysABP.x, Mean_SaO2.x, Mean_Albumin.x, Mean_ALP.x, Mean_ALT.x, Mean_AST.x, Mean_Bilirubin.x, Mean_Lactate.x, Mean_Cholesterol.x, Mean_TroponinI.x, Mean_TroponinT.x, Min_Weight.x, Min_GCS.x, Min_HR.x, Min_NIDiasABP.x, Min_NIMAP.x, Min_NISysABP.x, Min_RespRate.x, Min_Temp.x, Min_Urine.x, Min_BUN.x, Min_Creatinine.x, Min_Glucose.x, Min_HCO3.x, Min_GCT.x, Min_Mg.x, Min_Platelets.x, Min_K.x, Min_Na.x, Min_WBC.x, Min_pH.x, Min_PaCO2.x, Min_PaO2.x, Min_DiasABP.x, Min_FiO2.x, Min_MAP.x, Min_MechVent.x, Min_SysABP.x, Min_SaO2.x, Min_Albumin.x, Min_ALP.x, Min_ALT.x, Min_AST.x, Min_Bilirubin.x, Min_Lactate.x, Min_Cholesterol.x, Min_TroponinI.x, Min_TroponinT.x, Max_Weight.x, Max_GCS.x, Max_HR.x, Max_NIDiasABP.x, Max_NIMAP.x, Max_NISysABP.x, Max_RespRate.x, Max_Temp.x, Max_Urine.x, Max_BUN.x, Max_Creatinine.x, Max_Glucose.x, Max_HCO3.x, Max_GCT.x, Max_Mg.x, Max_Platelets.x, Max_K.x, Max_Na.x, Max_WBC.x, ...]
Index: []

[0 rows x 232 columns]

In [20]:
print(ICU.loc[[165, 1173], ['Age', 'Height']])

       Age  Height
165   87.0  159.02
1173  50.0  174.28